def get_seed_listings() -> list[dict]:
    return [
        {
            "address": "Via Roma 12, Lodi",
            "zone": "Lodi",
            "type": "affitto",
            "rooms": 2,
            "size_sqm": 55,
            "price": 750,
            "currency": "EUR",
            "available": True,
            "text": "Piano secondo, ascensore, posto auto incluso",
        },
        {
            "address": "Via Mazzini 45, Mulazzano",
            "zone": "Mulazzano",
            "type": "vendita",
            "rooms": 3,
            "size_sqm": 85,
            "price": 180000,
            "currency": "EUR",
            "available": True,
            "text": "Ottimo stato, cantina e box auto",
        },
        {
            "address": "Via Emilia 100, San Donato Milanese",
            "zone": "Milano Sud",
            "type": "affitto",
            "rooms": 3,
            "size_sqm": 120,
            "price": 1200,
            "currency": "EUR",
            "available": True,
            "text": "Ufficio open space, parcheggio privato",
        },
        {
            "address": "Corso Adda 8, Lodi",
            "zone": "Lodi",
            "type": "vendita",
            "rooms": 4,
            "size_sqm": 130,
            "price": 320000,
            "currency": "EUR",
            "available": True,
            "text": "Appartamento ristrutturato, terrazza, doppi servizi",
        },
        {
            "address": "Via Garibaldi 3, Lodi",
            "zone": "Lodi",
            "type": "affitto",
            "rooms": 1,
            "size_sqm": 35,
            "price": 550,
            "currency": "EUR",
            "available": True,
            "text": "Monolocale arredato, ideale per studenti",
        },
        {
            "address": "Via Torino 22, Mulazzano",
            "zone": "Mulazzano",
            "type": "vendita",
            "rooms": 2,
            "size_sqm": 60,
            "price": 120000,
            "currency": "EUR",
            "available": True,
            "text": "Bilocale piano terra con giardino privato",
        },
        {
            "address": "Via dei Mille 17, Peschiera Borromeo",
            "zone": "Milano Sud",
            "type": "affitto",
            "rooms": 3,
            "size_sqm": 80,
            "price": 1100,
            "currency": "EUR",
            "available": True,
            "text": "Trilocale luminoso, vicino fermata MM3",
        },
        {
            "address": "Via della Pace 5, Mulazzano",
            "zone": "Mulazzano",
            "type": "vendita",
            "rooms": 5,
            "size_sqm": 200,
            "price": 450000,
            "currency": "EUR",
            "available": True,
            "text": "Villetta a schiera con giardino, garage doppio",
        },
    ]
